/// <reference types="nativewind/types" />

// NOTE: This file should not be edited and should be committed with your source code. It is generated by NativeWind.

declare module "nativewind" {
  export interface CSSVariables {
    "--color-background": string;
    "--color-foreground": string;
    "--color-foreground-inverted": string;
    "--color-primary": string;
    "--color-primary-muted": string;
    "--color-secondary": string;
    "--color-secondary-foreground": string;
    "--color-accent": string;
    "--color-muted": string;
    "--color-muted-foreground": string;
    "--color-card": string;
    "--color-card-foreground": string;
    "--color-popover": string;
    "--color-popover-foreground": string;
    "--color-border": string;
    "--color-input": string;
    "--color-destructive": string;
    "--color-destructive-foreground": string;
    "--color-success": string;
    "--color-success-foreground": string;
    "--color-warning": string;
    "--color-warning-foreground": string;
    "--color-info": string;
    "--color-info-foreground": string;
  }
}